# updated Docker Kibana config
server.name: kibana
server.host: "0"
#elasticsearch.url: "http://es01:9200"
elasticsearch.hosts: "http://elasticsearch:9200"
xpack.monitoring.ui.container.elasticsearch.enabled: true
logging.events.log: ['warning','error','fatal','info','reporting']

